server:
  port: 7002

spring:
  application:
    name: SERVICE-USER

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-Url:
      defaultZone: http://localhost:8761/eureka/

