server:
  port: 7003

spring:
  application:
    name: SERVICE-DEPARTMENT

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-Url:
      defaultZone: http://localhost:8761/eureka/




